### ISSUE TITLE
test(test-tooling): fix flaky rustc-container-target-bundler

### ISSUE THREAD

**Issue by petermetz** [hyperledger-cacti/cacti#1626]
**Describe the bug**

Fix the flaky test, e.g. make it stable so that it always either fails or always succeeds.
The test file: `packages/cactus-test-tooling/src/test/typescript/integration/rustc-container/rustc-container-target-bundler.test.ts`

**To Reproduce**

Run it enough times to make it fail. (most of the time it succeeds)

**Expected behavior**

The test should be stable.

**Logs/Stack traces**

CI logs: [logs_11658.zip](https://github.com/hyperledger/cactus/files/7651744/logs_11658.zip)

```sh
2021-12-02T20:08:05.9467759Z     not ok 9 Error: Docker Exec timed out after 300000ms
2021-12-02T20:08:05.9469564Z       ---
2021-12-02T20:08:05.9470295Z         operator: error
2021-12-02T20:08:05.9480137Z         at: bound (/home/runner/work/cactus/cactus/node_modules/tape-promise/node_modules/onetime/index.js:30:12)
2021-12-02T20:08:05.9481438Z         stack: |-
2021-12-02T20:08:05.9482654Z           Error: Docker Exec timed out after 300000ms
2021-12-02T20:08:05.9484739Z               at Timeout._onTimeout (/home/runner/work/cactus/cactus/packages/cactus-test-tooling/src/main/typescript/common/containers.ts:102:13)
2021-12-02T20:08:05.9486349Z               at listOnTimeout (internal/timers.js:557:17)
2021-12-02T20:08:05.9487290Z               at processTimers (internal/timers.js:500:7)
2021-12-02T20:08:05.9488081Z       ...
2021-12-02T20:08:16.1465640Z     
2021-12-02T20:08:16.1487921Z     Bail out! Error: Docker Exec timed out after 300000ms
2021-12-02T20:08:16.1613711Z Bail out! Error: Docker Exec timed out after 300000ms
```

**Cloud provider or hardware configuration:**

Github Action Runner

**Operating system name, version, build:**

Ubuntu 20.04

**Hyperledger Cactus release version or commit (git rev-parse --short HEAD):**

`1.0.0-rc.2`

**Hyperledger Cactus Plugins/Connectors Used**

N/A

**Comment by RafaelAPB** [comment]
This issue will be considered if the depending package remains, as part of the cleanup initiative: https://github.com/hyperledger-cacti/cacti/issues/4037

**Comment by RafaelAPB** [comment]
Polkadot connector will be archived, so we can close this issue https://github.com/hyperledger-cacti/cacti/pull/4563
