### ISSUE TITLE
fix(quorum): connector container fails to run with quorum plugin

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger-cacti/cacti#2003]
**Describe the bug**

The quorum connector container fails to run with quorum plugin loaded as env var

**To Reproduce**

Create the `quorum-all-in-one` container image locally using
`DOCKER_BUILDKIT=1 docker build ./tools/docker/quorum-all-in-one/ -t qaio`

Run the above created aio using
`docker run --rm qaio`

Create the api-server container image loaded with quourum connector plugin locally using
`DOCKER_BUILDKIT=1 docker build -f ./packages/cactus-plugin-ledger-connector-quorum/Dockerfile . -t cplcb`

Run the above created image using
docker run \
  --rm \
  --publish 3000:3000 \
  --publish 4000:4000 \
  --env AUTHORIZATION_PROTOCOL='NONE' \
  --env AUTHORIZATION_CONFIG_JSON='{}' \
  --env PLUGINS='[{"packageName": "@hyperledger/cactus-plugin-ledger-connector-quorum", "type": "org.hyperledger.cactus.plugin_import_type.LOCAL", "action": "org.hyperledger.cactus.plugin_import_action.INSTALL",  "options": {"rpcApiHttpHost": "http://localhost:8545", "instanceId": "some-unique-quorum-connector-instance-id"}}]' \
  cplcb

**Expected behavior**

The `cplcb` image shall run without any errors

**Logs/Stack traces**

[2022-05-05T06:59:38.969Z] ERROR (api-server): ApiServer#instantiatePlugin failed instantiating plugin '@hyperledger/cactus-plugin-ledger-connector-quorum' with the instanceId 'some-unique-quorum-connector-instance-id' Error: Cannot find module 'run-time-error'
Require stack:
- /tmp/org/hyperledger/cactus/plugins/some-unique-quorum-connector-instance-id/node_modules/@hyperledger/cactus-plugin-ledger-connector-quorum/dist/lib/main/typescript/plugin-ledger-connector-quorum.js
- /tmp/org/hyperledger/cactus/plugins/some-unique-quorum-connector-instance-id/node_modules/@hyperledger/cactus-plugin-ledger-connector-quorum/dist/lib/main/typescript/public-api.js
- /tmp/org/hyperledger/cactus/plugins/some-unique-quorum-connector-instance-id/node_modules/@hyperledger/cactus-plugin-ledger-connector-quorum/dist/lib/main/typescript/index.js
- /usr/src/app/node_modules/@hyperledger/cactus-cmd-api-server/dist/lib/main/typescript/api-server.js
- /usr/src/app/node_modules/@hyperledger/cactus-cmd-api-server/dist/lib/main/typescript/cmd/cactus-api.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
    at Function.Module._load (node:internal/modules/cjs/loader:774:27)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/tmp/org/hyperledger/cactus/plugins/some-unique-quorum-connector-instance-id/node_modules/@hyperledger/cactus-plugin-ledger-connector-quorum/dist/lib/main/typescript/plugin-ledger-connector-quorum.js:25:26)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/tmp/org/hyperledger/cactus/plugins/some-unique-quorum-connector-instance-id/node_modules/@hyperledger/cactus-plugin-ledger-connector-quorum/dist/lib/main/typescript/public-api.js:15:40)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14) {
  code: 'MODULE_NOT_FOUND',

**Operating system name, version, build:**
Linux 5.13.0-40-generic x86_64
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Hyperledger Cactus release version or commit (git rev-parse --short HEAD):**

main branch code

**Hyperledger Cactus Plugins/Connectors Used**

Quorum connector plugin

**Comment by petermetz** [comment]
In the meantime we've deprecated the quorum connector.

**Comment by jagpreetsinghsasan** [comment]
Hahaha
